### **TASK 1**

In [26]:
import numpy as np

array = np.random.randint(10,51, size=(5,5))
print(array)

mean = np.mean(array)
median = np.median(array)
std = np.std(array)

maximum = np.max(array)
minimum = np.min(array)
max_idx = np.unravel_index(np.argmax(array), array.shape) 
min_idx = np.unravel_index(np.argmin(array), array.shape)

print(f'\nMean: {mean}, \nMedian: {median}, \nStandard Deviation: {std}')
print(f'Max: {maximum} at index {max_idx}, \nMin: {minimum} at index {min_idx}')

[[13 45 46 26 45]
 [35 11 14 26 48]
 [21 35 49 48 24]
 [18 13 21 35 11]
 [40 30 23 34 19]]

Mean: 29.2,
Median: 26.0,
Standard Deviation: 12.633289357883005
Max: 49 at index (np.int64(2), np.int64(2)),
Min: 11 at index (np.int64(1), np.int64(1))

### **TASK 2**

In [14]:
import scipy.stats as stats
import scipy.integrate as integrate

#Create a dataset
dataset = np.random.normal(loc=50, scale=10, size=100)

#Compute
mean_val = np.mean(dataset)
median_val = np.median(dataset)
mode_val = stats.mode(dataset, keepdims=True)
variance_val = np.var(dataset)
skewness_val = stats.skew(dataset)
kurtosis_val = stats.kurtosis(dataset)

print(f"Mean value: {mean_val}\n"
f"Median value: {median_val}\n"
f"Mode value: {mode_val}\n"
f"Variance: {variance_val}\n"
f"Skewness value: {skewness_val}\n"
f"Kurtosis value: {kurtosis_val}")

Mean value: 50.235117826799254
Median value: 51.452780437210265
Mode value: ModeResult(mode=array([31.44655322]), count=array([1]))
Variance: 74.9502900017577
Skewness value: -0.06779920280726205
Kurtosis value: -0.5478869625160372

### **TASK 3**

In [20]:
import pandas as pd
data = {
    'Name': ['Sam', 'Bobby', 'Abby', 'David', 'Matts'],
    'Age': [24, 27, 22, 32, 29],
    'Salary': [58000, 64000, 49500, 82000, 15000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Finance']
}
df = pd.DataFrame(data)

extra_rows = pd.DataFrame({
    'Name': ['Ngan','Lisa','Jenny','Rose','Anna','Leon','John','Kate','Julia','Tom'],
    'Age': [25,20,23,24,27,28,20,21,30,26],
    'Salary': [80000,72000,33000,25000,68000,24500,54000,31500,42000,28000],
    'Department': ['IT','Finance', 'HR', 'IT', 'Finance','IT','HR', 'Finance', 'IT', 'Finance']
})

df = pd.concat([df, extra_rows], ignore_index=True)

df.head()

    Name  Age  Salary Department
0    Sam   24   58000         HR
1  Bobby   27   64000         IT
2   Abby   22   49500    Finance
3  David   32   82000         IT
4  Matts   29   15000    Finance

In [21]:
df.tail()

     Name  Age  Salary Department
10   Leon   28   24500         IT
11   John   20   54000         HR
12   Kate   21   31500    Finance
13  Julia   30   42000         IT
14    Tom   26   28000    Finance

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        15 non-null     object
 1   Age         15 non-null     int64
 2   Salary      15 non-null     int64
 3   Department  15 non-null     object
dtypes: int64(2), object(2)
memory usage: 612.0+ bytes

In [23]:
df.describe()

             Age        Salary
count  15.000000     15.000000
mean   25.200000  48433.333333
std     3.668398  21796.024102
min    20.000000  15000.000000
25%    22.500000  29750.000000
50%    25.000000  49500.000000
75%    27.500000  66000.000000
max    32.000000  82000.000000

In [25]:
df['Bonus'] = df['Salary']*0.10
print(df)

     Name  Age  Salary Department   Bonus
0     Sam   24   58000         HR  5800.0
1   Bobby   27   64000         IT  6400.0
2    Abby   22   49500    Finance  4950.0
3   David   32   82000         IT  8200.0
4   Matts   29   15000    Finance  1500.0
5    Ngan   25   80000         IT  8000.0
6    Lisa   20   72000    Finance  7200.0
7   Jenny   23   33000         HR  3300.0
8    Rose   24   25000         IT  2500.0
9    Anna   27   68000    Finance  6800.0
10   Leon   28   24500         IT  2450.0
11   John   20   54000         HR  5400.0
12   Kate   21   31500    Finance  3150.0
13  Julia   30   42000         IT  4200.0
14    Tom   26   28000    Finance  2800.0

In [27]:
high_salary = df[df['Salary'] > 55000]
high_salary

    Name  Age  Salary Department   Bonus
0    Sam   24   58000         HR  5800.0
1  Bobby   27   64000         IT  6400.0
3  David   32   82000         IT  8200.0
5   Ngan   25   80000         IT  8000.0
6   Lisa   20   72000    Finance  7200.0
9   Anna   27   68000    Finance  6800.0

Done!