## Using Pandas

**Data Dictionary**

* Name - Name of the person
* Net worth in billions - Net worth of the person in billions
* Country - Country where the person is from
* Source - Source of the income
* Rank - Rank of the person in the Billionaires list
* Age - Age of the person
* Industry - Industry to which the person is related to

### Importing Pandas Library

In [2]:
import pandas as pd

### Loading the dataset in a pandas dataframe

In [34]:
df = pd.read_csv('Forbes-list-2020.csv')
print(df)

                          Name  NetWorth in billions        Country  \
0                   Jeff Bezos                 177.0  United States
1                    Elon Musk                 151.0  United States
2     Bernard Arnault & family                 150.0         France
3                   Bill Gates                 124.0  United States
4              Mark Zuckerberg                  97.0  United States
...                        ...                   ...            ...
2750         Daniel Yong Zhang                   1.0          China
2751             Zhang Yuqiang                   1.0          China
2752             Zhao Meiguang                   1.0          China
2753            Zhong Naixiong                   1.0          China
2754           Zhou Wei family                   1.0          China

             Source  Rank  Age          Industry
0            Amazon     1   57        Technology
1     Tesla, SpaceX     2   49        Automotive
2              LVMH     3   72  Fashion & Retail
3         Microsoft     4   65        Technology
4          Facebook     5   36        Technology
...             ...   ...  ...               ...
2750     e-commerce  2674   49        Technology
2751     Fiberglass  2674   65     Manufacturing
2752    gold mining  2674   58   Metals & Mining
2753   conglomerate  2674   58       Diversified
2754       Software  2674   54        Technology

[2755 rows x 7 columns]

### Print top 5 rows

In [5]:
print('Ngan Nguyen')
df.head(5)

Ngan Nguyen

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry
0,Jeff Bezos,177.0,United States,Amazon,1,57,Technology
1,Elon Musk,151.0,United States,"Tesla, SpaceX",2,49,Automotive
2,Bernard Arnault & family,150.0,France,LVMH,3,72,Fashion & Retail
3,Bill Gates,124.0,United States,Microsoft,4,65,Technology
4,Mark Zuckerberg,97.0,United States,Facebook,5,36,Technology

#### <span style="color:crimson">Q1. Whose name is assigned to the 0th index in the dataframe</span>

In [36]:
df.loc[0,"Name"]

'Jeff Bezos'

### Print the dimensions of data

#### <span style="color:crimson">Q2. How many records do you have in this dataset?</span>

In [37]:
df.shape[0]

2755

#### <span style="color:crimson">Q3. What is the data type of the variable Source</span>

In [38]:
df["Source"].dtype

dtype('O')

### Checking for missing values

#### <span style="color:crimson">Q4. How many missing values exists in the industry feature</span>

In [42]:
print(df['Industry'].isnull().sum())

0

### Print the basic stats for this dataset

#### <span style="color:crimson">Q5. Who is the yongest billionare in this list?</span>

In [19]:
df.loc[df['Age'].idxmin(),'Name']

'Kevin David Lehmann'

#### <span style="color:crimson">Q6. What is the output of `df.iloc[1200,3]`?</span>

In [20]:
df.iloc[1200,3]

'real estate'

### Create a new column `Year_of_birth`
Note: The dataset is from the year 2020. The age of those Billionaires is as of 2020.

In [22]:
# create a new column 'Year_of_birth'
df['Year_of_birth'] = 2020 - df['Age']

In [23]:
#view the data
df

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry,Year_of_birth
0,Jeff Bezos,177.0,United States,Amazon,1,57,Technology,1963
1,Elon Musk,151.0,United States,"Tesla, SpaceX",2,49,Automotive,1971
2,Bernard Arnault & family,150.0,France,LVMH,3,72,Fashion & Retail,1948
3,Bill Gates,124.0,United States,Microsoft,4,65,Technology,1955
4,Mark Zuckerberg,97.0,United States,Facebook,5,36,Technology,1984
...,...,...,...,...,...,...,...,...
2750,Daniel Yong Zhang,1.0,China,e-commerce,2674,49,Technology,1971
2751,Zhang Yuqiang,1.0,China,Fiberglass,2674,65,Manufacturing,1955
2752,Zhao Meiguang,1.0,China,gold mining,2674,58,Metals & Mining,1962
2753,Zhong Naixiong,1.0,China,conglomerate,2674,58,Diversified,1962
2754,Zhou Wei family,1.0,China,Software,2674,54,Technology,1966

### Select Billionaires born in 1996

In [28]:
# Using where condition
df.where(df["Year_of_birth"] == 1996).dropna()

,Name,NetWorth in billions,Country,Source,Rank,Age,Industry,Year_of_birth
2122,Wang Zelong,1.5,China,chemicals,2035.0,24.0,Metals & Mining,1996.0
2143,Alexandra Andresen,1.4,Norway,investments,2141.0,24.0,Diversified,1996.0

#### <span style="color:crimson">Q7. How many Billionaires were born in 1996?</span>

In [31]:
df[df["Year_of_birth"] == 1996].shape[0]

2